### ISSUE TITLE
Google, Microsoft and Cloudflare not Working

### ISSUE THREAD

**Issue by martinherweg** [willfarrell/alfred-cdn-workflow#6]
Hello,

would be nice if you can fix the search for google, Microsoft and Cloudflare.

At least for me, no matter what I search i get no results from these 3 Services as you can see in the Screenshot.

Thanks :)

![image](https://cloud.githubusercontent.com/assets/381383/14497366/04bab830-0197-11e6-8ea0-32d37c6bd77e.png)

**Comment by willfarrell** [comment]
I'm getting the same thing, thanks for posting the issue. I should have time early next week to dig into it.

**Comment by willfarrell** [comment]
google and microsoft now fixed in v1.5
url and html parsers were out of date.
Looking into cloudflare

**Comment by willfarrell** [comment]
another update pushed.
